Ajax
Navarrskij/stack pull request #20
Opened 2016-10-28 13:28 UTC by Navarrskij

2016-10-28 19:43 UTC, palkan requested changes

2016-10-28 19:43 UTC, palkan commented on app/models/answer.rb
> +  	self.update_attributes best: true
Во-первых, `update`: короче, а делает то же самое. А здесь вообще нужен `update!`.

Во-вторых, нужно обернуть вызовы в транзакцию, чтобы в случае падения второго запроса у нас откатывался первый.

2016-10-28 20:28 UTC, Navarrskij commented on app/models/answer.rb
> +  	self.update_attributes best: true
по поводу update немного не понял. с update! падает undefined method `update!' for #<ActiveRecord::Associations::CollectionProxy

2016-10-28 20:36 UTC, palkan commented on app/models/answer.rb
> +  	self.update_attributes best: true
Ну так ты не тем его пишешь) `self.update!` (лучше даже без `self`, просто `update!`).

2016-10-28 21:00 UTC, Navarrskij commented on app/models/answer.rb
> +  	self.update_attributes best: true
а..блин) сорри, что нашел первым взглядом, туда и тупил) понял, обещаю исправить:)

2016-10-29 09:18 UTC, vkurennov approved these changes
Принято, но поправь замечания

2016-10-29 09:18 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @answer.best!
Если в if одна строка, записывай с постфиксным if: `@answer.best!  if current_user.author_of?(@answer.question)`

2016-10-29 09:18 UTC, vkurennov commented on app/models/answer.rb
> +  	transaction do
Что с отступами? Должно быть ровно 2 пробела, не таба, а именно пробела.

2016-10-29 09:18 UTC, vkurennov commented on app/models/answer.rb
> +  		update! best: true
Параметры методов заключай в скобки

2016-10-29 09:26 UTC, Navarrskij commented on app/models/answer.rb
> +  	transaction do
1 таб в 2 пробела... именно так.. но почему отображается криво именно этот файл

2016-10-29 14:33 UTC, merged