Vote
Navarrskij/stack pull request #22
Opened 2016-11-09 23:45 UTC by Navarrskij

2016-11-10 08:53 UTC, vkurennov requested changes

2016-11-10 08:53 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes.where(votable: self).sum(:value)
Смысла where добавлять нет. Мы же вызываем эти методы в контексте конкретного объекта, поэтому обращаяс к ассоциации votes уже ограничиваем скоуп этим объектом. Иными словами,  where(votable: self) добавляется автоматом при обращении к votes

2016-11-10 08:53 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def was_vote_up?(user)
Этот и следующий методы я бы вынес в модель User, тогда мы бы у юзера "спрашивали" голосовал он или нет за такой-то объект

2016-11-10 08:53 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    success, error = @votable.vote_up(current_user)
Не нравится мне эта идея с возвратом 2-х значений, не первый раз уже ее вижу. Почему бы не возвращать true/false, например, как это с save происходит? А ошибку (она одна всего) разруливать на уровне контроллера?

2016-11-10 08:53 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def vote_down(user)
Код методов vote_up и vote_down отличается только парой строк. Подумай, как его сделать более универсальным.

2016-11-10 08:53 UTC, vkurennov commented on app/models/vote.rb
> +	belongs_to :votable, polymorphic: true, optional: true
Что с отступами?

2016-11-10 08:53 UTC, vkurennov commented on app/models/vote.rb
> +	belongs_to :votable, polymorphic: true, optional: true
И почему optional: true? Разве может голос существовать без привязки к объекту?

2016-11-10 08:53 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +    <%= link_to 'vote up', vote_up_answer_path(answer), method: :patch, remote: true, data: { type: :json} %><br>
Т.е. мы обе ссылки показываем всегда? Вне зависимости от того, голосовал юзер уже или нет и как он голосовал? Надо хотя бы показывать, что юзер уже голосовал

2016-11-10 08:53 UTC, vkurennov commented on app/views/questions/show.html.slim
> +div id='question_= @question.id'
Это же не исполняемая строка, т.е. у тебя не подставится сюда id. Для этого надо использовать двойные кавычки и интерполяцию (#{})

2016-11-10 08:53 UTC, vkurennov commented on spec/acceptance/vote_answer_spec.rb
> +      expect(page).to have_content "Don't vote it post"
Может, ему вообще ссылку не показывать на голоосвание?

2016-11-10 08:53 UTC, vkurennov commented on spec/acceptance/vote_question_spec.rb
> +    expect(page).to have_content "Don't vote it post"
Фраза сама по себе, конечно, странная :-)

2016-11-10 08:53 UTC, vkurennov commented on spec/factories/votes.rb
> + 		votable { |v| v.association(:question) }
Что опять с отступами?

2016-11-10 08:53 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +    context 'positive vote' do
Все можно протестировать в 1-м тесте, создаешь несколько положительных и отрицательных голосов и проверяешь общую сумму.

2016-11-10 08:53 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +    context 'when have votes up' do
Ну тогда должен быть и контекст, когда юзер не голосовал или голосовал против

2016-11-10 08:53 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +      it {expect(model.rating).to eq(1) }
А почему ты проверяешь рейтинг, если тест на метод `was_vote_up?`? Вот этот метод и тестируй

2016-11-10 08:53 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +      it { expect(model.rating).to eq(-1) }
И опять, почему ты тестируешь другой метод? как это проверяет работу метода `was_vote_down?`

2016-11-10 08:53 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +  describe 'vote_up' do
Нужно еще проверить возвращаемые значения метода в том или ином контексте.

2016-11-10 08:53 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +  describe 'vote_down' do
И тут надо проверить возвращаемые значения

2016-11-10 12:07 UTC, Navarrskij commented on app/models/vote.rb
> +	belongs_to :votable, polymorphic: true, optional: true
фигня какая-то... настроен редактор на таб = 2 пробела. в редакторе все путем с отступами, а в PR как-то выборчно двигается, так съехало, там нет.. не могу понять в чем причина..ты уже как-то обращал на это внимание

2016-11-10 12:09 UTC, Navarrskij commented on app/views/questions/show.html.slim
> +div id='question_= @question.id'
странно.. именно так у меня работает)

2016-11-10 15:18 UTC, Navarrskij commented on app/models/concerns/votable.rb
> +  def was_vote_up?(user)
А в чем смысл? кода не уменшится, тестов тоже...тут хоть все в одном месте касательно голосования. Может поиск в базе меньше времени займет?

2016-11-10 17:04 UTC, Navarrskij commented on app/views/answers/_answer.html.erb
> +    <%= link_to 'vote up', vote_up_answer_path(answer), method: :patch, remote: true, data: { type: :json} %><br>
как это сделать? запилить метод - другой на то, если было например was_vote_up - то не показывать эту ссылку. тогда останется рейтинг и одна из ссылок - как-то не то...видимо нужно как-то выделять через вьюхи и css которого у меня пока нет:)

2016-11-11 08:57 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def was_vote_up?(user)
Нет, смысл в проектирование, к чему относится метод, кто является объектом, а кто субъектом. В данном случае, объект  - это скорее пользователь. Ну и надо понимать, что консерн - это модуль, он включается в разные классы, а значит, у каждого класса появятся эти методы проверки. Для методов голосования - это ок, т.к. мы голосуем **за объект**. А вот для проверок  - не очень

2016-11-11 08:59 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +    <%= link_to 'vote up', vote_up_answer_path(answer), method: :patch, remote: true, data: { type: :json} %><br>
Как раз через проверки was_vote_up и т.п. Но, в принципе, это вопрос к UI больше, так что оставим его за скобками

2016-11-11 08:59 UTC, vkurennov commented on app/views/questions/show.html.slim
> +div id='question_= @question.id'
Конечно не заработает :-)

2016-11-11 09:11 UTC, vkurennov requested changes
Исправь замечания

2016-11-11 09:11 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +end
Что-то end съехал

2016-11-11 09:11 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    votes.find_by(user: user, value: -1).present?
кстати, используй exists? вместо present? в этом случае, объект в память из базы не загружается

2016-11-11 09:11 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +      it { expect(model.rating).to eq(0) }
0 - опасное число, т.к. возвращается даже если в базе нет голосов. лучше либо положительное, либо отрицательное число проверить, так есть хоть какая-то уверенность, что данные влияют на результат

2016-11-11 09:11 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +    context "on other user post" do
Нет смысла делать контекст с 1 тестом, пиши описание тогда в тесте

2016-11-11 09:11 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +  describe 'vote_up' do
Я не увидел проверку возвращаемых значений. То, что метод что-то меняет, ок, это проверили. А вот то, что он при этом вернул - нет

2016-11-11 09:11 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +  describe 'vote_down' do
И тут тестируется только изменение рейтинга, а то, что метод возвращает не тестируется.

2016-11-11 12:21 UTC, Navarrskij commented on app/models/concerns/votable.rb
> +  def was_vote_up?(user)
когда буду рефакторить виды по-человечески, тогда видимо придется перенести, чтобы делать подсветку когда проголосовал... если другого ничего не придумается

2016-11-11 12:22 UTC, Navarrskij commented on app/controllers/concerns/voted.rb
> +end
сорри... недоглядел

2016-11-11 14:16 UTC, Navarrskij commented on spec/models/concern/votable_spec.rb
> +  describe 'vote_up' do
возвращает "правильный" рейтинг насколько я понял)

2016-11-11 20:13 UTC, vkurennov requested changes

2016-11-11 20:13 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +  describe 'vote_up' do
Нет. Посмотри что на самом деле возвращает метод и в каких условиях. Рейтинг возвращает метод rating, а эти методы работают по-другому, это важно, т.к. возвращаемые значение используются в контроллере.

Должны быть тесты: без ошибок возвращаем то-то, если есть ошибки то-то. Пока таких тестов не будет, дальше не пойдем.

2016-11-11 20:13 UTC, vkurennov commented on spec/models/concern/votable_spec.rb
> +      expect(model.rating).to eq(1)
В юнит-тестах действует принцип "один тест - одни expect".  И кроме рейтинга нам нужно тестировать, что возвращает метод и в каких случаях. Посмотри на код метода.

2016-11-12 10:01 UTC, vkurennov approved these changes

2016-11-12 11:03 UTC, merged