Oauth
Navarrskij/stack pull request #25
Opened 2016-12-02 19:29 UTC by Navarrskij

2016-12-03 08:12 UTC, vkurennov requested changes

2016-12-03 08:12 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +	def facebook
Что с отступами?

2016-12-03 08:12 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user.persisted?
А если нет, что тогда? А будет 500-я ошибка. Надо этот кейс покрыть тестами и не показывать юзеру 500-ю ошибку, а что-то разумное написать

2016-12-03 08:12 UTC, vkurennov commented on spec/models/user_spec.rb
> +    context 'user has not authorization' do
Ставь пустые строки между контекстами и тестами

2016-12-03 13:19 UTC, Navarrskij commented on app/controllers/omniauth_callbacks_controller.rb
> +	def facebook
оно само:) исправил.. кажется  причина а лишних пробелах на конце предыдущей строки..  а кк они возникают - не понятно

2016-12-03 13:21 UTC, Navarrskij commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user.persisted?
ну да. думаю разумно перенаправит на путь регистрации. а вот по поводу тестов...этоже вроде приватный метод , да  и  вроде как протестированы в модели и ацептанс спеках

2016-12-04 09:15 UTC, vkurennov approved these changes

2016-12-04 10:11 UTC, merged